added product and order creation
vojtko84/altexsoft-lab-2021 pull request #3
Opened 2021-04-22 15:04 UTC by vojtko84

added product and order creation

2021-04-27 02:05 UTC, serhii-shkodenko requested changes

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/CategoryController.cs
> +        public CategoryController(Context context)
Нарушен Dependency Inversion Principle. Используй интерфейсы.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/DeliveryAddressController.cs
> +        public DeliveryAddressController(Context context)
Нарушен Dependency Inversion Principle. Используй интерфейсы.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/OrderController.cs
> +        public OrderController(Context context)
Нарушен Dependency Inversion Principle. Используй интерфейсы.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/ProductController.cs
> +        public ProductController(Context context)
Нарушен Dependency Inversion Principle. Используй интерфейсы.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +        public Presenter(Context context)
Нарушен Dependency Inversion Principle. Используй интерфейсы.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            userController = new UserController();
Нарушен Dependency Inversion Principle. Добавь эту зависимость в конструктор и сделай инъекцию. Используй интерфейс.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            productController = new ProductController(context);
Нарушен Dependency Inversion Principle. Добавь эту зависимость в конструктор и сделай инъекцию. Используй интерфейс.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            categoryController = new CategoryController(context);
Нарушен Dependency Inversion Principle. Добавь эту зависимость в конструктор и сделай инъекцию. Используй интерфейс.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            deliveryAddressController = new DeliveryAddressController(context);
Нарушен Dependency Inversion Principle. Добавь эту зависимость в конструктор и сделай инъекцию. Используй интерфейс.

2021-04-27 02:05 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            orderController = new OrderController(context);
Нарушен Dependency Inversion Principle. Добавь эту зависимость в конструктор и сделай инъекцию. Используй интерфейс.

2021-04-29 20:36 UTC, serhii-shkodenko requested changes
Поправь эти несколько мелочей и будет аппрув.

2021-04-29 20:36 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Interfaces/IUser.cs
> +    public interface IUser
Использовать пустые интерфейсы, это не очень хорошая идея. Лучше от него избавиться.

2021-04-29 20:36 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Interfaces/IDeliveryAddressController.cs
> +namespace Mydelivery.Interfaces
Согласно [конвенциям](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces), этот неймспейс лучше переименовать в `MyDelivery`. Просмотри весь ПР, пожалуйста.

2021-04-29 20:36 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/UserController.cs
> +        public IUser SelectUser(string selectedUser)
Лучше переназвать этот метод на, например, `SelectUserType`, то есть отобразить в имени то, что выбирается тип пользователя.

2021-04-30 19:27 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            var buyerId = ((Buyer)userController.User).Id;
Здесь нет нужды делать приведение типов, потому что тип `Buyer` унаследован от типа `User`, который имеет свойство `Id`. Поскольку свойство `userController.User` имеет тип User, ты уже имеешь доступ к `Id`.

2021-04-30 19:28 UTC, serhii-shkodenko commented on mydelivery/mydelivery/UI/Presenter.cs
> +            var sellerId = ((Seller)userController.User).Id;
Здесь нет нужды делать приведение типов, потому что тип `Seller` унаследован от типа `User`, который имеет свойство `Id`. Поскольку свойство `userController.User` имеет тип User, ты уже имеешь доступ к `Id`.

2021-04-30 20:39 UTC, serhii-shkodenko requested changes
Забыл поправить в других местах моменты с Id. Поправь, пожалуйста.

2021-04-30 20:39 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/CategoryController.cs
> +                Id = context.Categories.Count + 1,
Исправленную логику нахождения максимального Id здесь тоже лучше применить.

2021-04-30 20:39 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/OrderController.cs
> +                Id = context.Orders.Count + 1,
Исправленную логику нахождения максимального Id здесь тоже лучше применить.

2021-04-30 20:39 UTC, serhii-shkodenko commented on mydelivery/mydelivery/Controllers/DeliveryAddressController.cs
> +                Id = context.DeliveryAddresses.Count + 1,
Исправленную логику нахождения максимального Id здесь тоже лучше применить.

2021-04-30 20:53 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-04-30 21:04 UTC, vojtko84 commented
> Выглядит хорошо, можно мержить.

Спасибо за найденные ошибки в логике. Потом бы я долго думал что не так с моими списками))

2021-04-30 21:04 UTC, merged